name: Build & Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build_android:
    name: Build & Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Decode Keystore
        if: env.ANDROID_KEYSTORE_BASE64 != ''
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: echo "$ANDROID_KEYSTORE_BASE64" | base64 -d -i > android/app/release-key.jks

      - name: Build APK
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: flutter build apk --release

      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/UntisNeo.apk

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/UntisNeo.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Appetize Github Action
        uses: appetizeio/github-action-appetize@v1.0.5
        with:
          file_path: build/app/outputs/flutter-apk/UntisNeo.apk
          api_token: ${{ secrets.APPETIZE_API_TOKEN }}

  build_windows:
    name: Build & Release Windows EXE
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Ensure Windows Platform
        run: flutter create --platforms=windows .

      - name: Build Windows
        run: flutter build windows --release

      - name: Zip Windows Build
        run: Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath UntisNeo-Windows.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: UntisNeo-Windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_web:
    name: Build & Release Web
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Ensure Web Platform
        run: flutter create --platforms=web .

      - name: Build Web
        run: flutter build web --release --base-href "/Untis_Neo/"

      - name: Zip Web Build
        run: |
          cd build/web
          zip -r ../../UntisNeo-Web.zip .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: UntisNeo-Web.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
